### ISSUE TITLE
1.20.1 Modpack crashing after today's update

### ISSUE THREAD

**Issue by PlagueVessel** [ItsBlackGear/VanillaBackport#124]
MC Ver: 1.20.1
Forge Ver: 47.4.0

Playing with essential and never had a problem with the backport. today after the update my friends cant get into the world without crashing with the following message:

java.lang.NoClassDefFoundError: Could not initialize class com.blackgear.vanillabackport.common.level.entities.wolf.WolfVariants

Tried to do a downgrade from the mod version but it bricks the world datapack and cant load the game.

**Comment by ItsBlackGear** [comment]
i'll take a look into it right away

**Comment by PlagueVessel** [comment]
Thanks for the quick response. I'll stay alert for any info you need.

**Comment by ItsBlackGear** [comment]
feel free to join the discord server, i can provide a jar file before release

**Comment by ItsBlackGear** [comment]
1.1.5.1 should fix the issue

**Comment by PlagueVessel** [comment]
I'll take a look and test it before closing the thread.

**Comment by PlagueVessel** [comment]
Ok so game still crashes but error message is referent to pigs this time

The game crashed: unexpected error
Error: java.lang.NoClassDefFoundError: Could not initialize class com.blackgear.vanillabackport.common.level.entities.animal.PigVariants

**Comment by Clairetee1223** [comment]
Having same issue, even on 1.1.5.1 keep getting Exit Code: 1 
`The game crashed: rendering overlay
Error: java.lang.IllegalArgumentException: Failed to create model for minecraft:wolf`

Peeking at the crash report, it says: 
`Caused by: java.lang.IllegalArgumentException: No model for layer minecraft:wolf_armor#main
	at net.minecraft.client.model.geom.EntityModelSet.m_171103_(EntityModelSet.java:17) ~[client-1.20.1-20230612.114412-srg.jar%23418!/:?] {re:mixin,re:classloading}
	at com.blackgear.vanillabackport.client.level.entities.layer.WolfArmorLayer.<init>(WolfArmorLayer.java:44) ~[vanillabackport-forge-1.20.1-1.1.5.jar%23410!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}`

I'm thinking it could be an issue with a rendering mod, like Moonlight or Flywheel? I'm gonna test a bit lol

**Comment by Clairetee1223** [comment]
Tested it, removing Flywheel allowed the game to launch without an issue, but now there seems to be an issue with Essential's cosmetics, and creating/loading a world crashes the game.
